### ISSUE TITLE
No function "load" in trait epi::App

### ISSUE THREAD

**Issue by rednaz1337** [emilk/egui_template#12]
Hi, when the template is compiled with the "persistence" feature, it fails to compile it, because there is no "load" function in the trait epi::App, only a "setup" function.

**Comment by bjorn** [comment]
The template needs to be adjusted to this API change: https://github.com/emilk/egui/commit/44b573f6a6fc552b4315d48eb672b01ed96caca4.

**Comment by emilk** [comment]
Thanks! Fixed in https://github.com/emilk/egui_template/pull/20
