### ISSUE TITLE
Fails with xcb error on startup

### ISSUE THREAD

**Issue by JanneM** [emilk/egui_template#18]
Under Linux (X11, Manjaro ARM) the demo app fails with:

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
egui_template: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Avbruten (SIGABRT) (minnesutskrift skapad)

Edit: Updated rust toolchain from 1.51 ro 1.52. Now trying to run with either release or debug (just "cargo run") gives me:

ibEGL warning: DRI2: failed to authenticate

I have all xcb libraries I can find installed. Any test or further investigation you'd like me to do, just let me know.

Edit 2: I was using software rendering on the machine for some reason. Once I switched to the Panfrost mesa driver it all worked.

Thank you for coming to my monologue, and I hope you've had an enjoyable evening. Feel free to delete this issue if you like.

**Comment by JanneM** [comment]
Problem found between keyboard and screen. Closing.

**Comment by Piping** [comment]
I got the same error on debian inside a virtual machine. 

```
uname -a
Debian 5.15.5-1 (2021-11-26) aarch64 GNU/Linux
```

Does it mean that egui currently cannot run in virtual machine where only software render is available?
