### ISSUE TITLE
Demo app text box fails to bring up iOS keyboard

### ISSUE THREAD

**Issue by placrosse** [emilk/egui_template#2]
Attempting to use demo app at

https://emilk.github.io/egui_template/

and edit the text box results in no virtual keyboard being displayed, even though text box has focus and cursor within the text.

Using iOS 14.3 on iPhone XR, but also verified same results on iPhone 12 with iOS 14.4

**Comment by emilk** [comment]
Thanks for the report!

This is a known shortcoming in `egui_web` but appearantly I haven't opened a ticket for it, so I did so now: https://github.com/emilk/egui/issues/147
