### ISSUE TITLE
minimum for build an egui application

### ISSUE THREAD

**Issue by jcbritobr** [emilk/egui_template#23]
Cant understand what is the minimum to write an agui application. What are the minimum dependencies? The minimum code necessary to get a simple example running.

**Comment by emilk** [comment]
This repo is pretty close to a minimum, though it can be stripped down more if you don't care about publishing to web. A smaller example can be found at https://github.com/emilk/egui/blob/master/eframe/examples/hello_world.rs

**Comment by jcbritobr** [comment]
> 
> 
> This repo is pretty close to a minimum, though it can be stripped down more if you don't care about publishing to web. A smaller example can be found at https://github.com/emilk/egui/blob/master/eframe/examples/hello_world.rs

thats is what i need.
