### ISSUE TITLE
Provide a simpler example using egui?

### ISSUE THREAD

**Issue by jpggithub** [emilk/egui_template#6]
Hi
I have been trying to use egui for several hours and days and I don't understand how to use egui simply.
I'm not a pro dev but I've already buid UI with python.
I can compile the actual egui_template but can you provide a (the most?) simpler and complete example using egui?
Another option could be a basic tutorial? I didn't found one on the web.
Thanks anyway, the actual egui example is very convincing!

**Comment by bjorn** [comment]
There are simpler examples for various framework integrations. For example:

* For eframe, see "Hello World" example at https://github.com/emilk/egui/blob/master/eframe/examples/hello_world.rs
* For bevy_egui, see "Hello World" example at https://github.com/mvlabat/bevy_egui/blob/main/examples/simple.rs

As you can see these examples depend a lot on what framework you're using egui with, which might be why they're not included with egui itself.

**Comment by emilk** [comment]
I've simplified the code in this template a bit, but it is hard to keep it both simple and complete, as I want this template to work both for native and for web.

If you only want to compile for native, than the first link @bjorn posted is as simple as it gets.
