### ISSUE TITLE
Use serde(default) attribute for persistence state structs

### ISSUE THREAD

**Issue by Vanadiae** [emilk/egui_template#7]
Hi!

Currently if I do some things with the app template to have some things that change in the persistant state (e.g. if I click the increment button), then if I add a new field to the state's struct (`TemplateApp`) all the other fields are reset to their default value. This seems to be because serde doesn't know what to do with the field which isn't in the persistent state, so it kinda refuses to deserialize altogether, yielding None in the `load()` function, hence resetting _all_ the struct to the default with the `unwrap_or_default()`. It seems like egui's main demo [has this `#[serde(default)]` line](https://github.com/emilk/egui/blob/2f46c975a578fbffdf74139102d75b4d3af5d2a2/egui_demo_lib/src/wrap_app.rs#L4) so it seems like someone encountered this issue too at some point :).

It would be useful to add a comment explaining why it's there so that people actually understand what it's for.

Do you want me to create a PR or is it easy enough that you don't mind doing it? `:)`

**Comment by emilk** [comment]
Good idea!
