### ISSUE TITLE
How can the grey margins on the web version be removed?

### ISSUE THREAD

**Issue by olivereanderson** [emilk/egui_template#8]
The start page for my app looks like this natively: 
![image](https://user-images.githubusercontent.com/50836158/119521827-c8a7cf80-bd7b-11eb-8574-c281b395b1b0.png)
and like this on the web (I am using Firefox):
![image](https://user-images.githubusercontent.com/50836158/119522048-f55be700-bd7b-11eb-8c3a-2404aed33583.png)
It has the same grey margins as the demo: 
![image](https://user-images.githubusercontent.com/50836158/119521124-2556ba80-bd7b-11eb-9439-e35b519809e2.png)

How may one remove these?

**Comment by bjorn** [comment]
This limit is applied here (with a comment explaining the reason):

https://github.com/emilk/egui/blob/196ddff499e7e27c0abf3119ac93fd5df81cb081/epi/src/lib.rs#L138-L142

It can be changed by overriding this function for your app, as done for the demo app here:

https://github.com/emilk/egui/blob/196ddff499e7e27c0abf3119ac93fd5df81cb081/egui_demo_lib/src/wrap_app.rs#L53-L55
